language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

sudo: required

services:
    - docker

install:
    - pip install -r requirements.txt

script:
    - python -m pytest -s tests/

after_success:
    - if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then docker build -t theialog/theia:latest . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push theialog/theia:latest ; fi

